jobs:
  include:
    - name: "20.04 flake8 and native run (py3.8)"
      os: linux
      dist: focal
      language: shell
      install: sudo apt-get update; sudo apt install flake8 python3-pexpect;
      script:
        - "flake8 sos tests bin/*"
        - "sudo ./tests/simple.sh"
    - name: "18.04 pycodestyle and native run (py3.6)"
      os: linux
      dist: bionic
      language: shell
      install: sudo apt-get update; sudo apt install python3-pexpect;
      script: "sudo ./tests/simple.sh"
    - name: "18.04 native run for arm64"
      os: linux
      dist: bionic
      arch: arm64
      language: shell
      script: "sudo ./tests/simple.sh"
    - name: "18.04 native s390x"
      os: linux
      dist: bionic
      arch: s390x
      language: shell
      script: "sudo ./tests/simple.sh"
    - name: "nosetests and travis Python 3.6"
      os: linux
      dist: bionic
      language: python
      python: "3.6"
      install: pip install -r test-requirements.txt; python3 setup.py install;
      script:
        - "nosetests -v --with-cover --cover-package=sos --cover-html"
        - "sudo ./tests/simple.sh ~/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/python"
    - name: "nosetests and travis Python 3.7"
      os: linux
      dist: bionic
      language: python
      python: "3.7"
      install: pip install -r test-requirements.txt; python3 setup.py install;
      script:
        - "nosetests -v --with-cover --cover-package=sos --cover-html"
        - "sudo ./tests/simple.sh ~/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/python"
    - name: "nosetests and travis Python 3.8"
      os: linux
      dist: bionic
      language: python
      python: "3.8"
      install: pip install -r test-requirements.txt; python3 setup.py install;
      script:
        - "nosetests -v --with-cover --cover-package=sos --cover-html"
        - "sudo ./tests/simple.sh ~/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/python"

notifications:
  email:
    sos-devel@redhat.com
  irc:
    channels:
      - "us.freenode.net#sosreport"
    on_success: change
git:
  depth: 20
