jobs:
  include:
    - name: "18.04 pycodestyle and native run (py3.6)"
      os: linux
      dist: bionic
      language: shell
      install: sudo apt-get update; sudo apt install pycodestyle;
      script:
        - "pycodestyle sos"
        - "sudo ./tests/simple.sh"
    - name: "18.04 native run for arm64"
      os: linux
      dist: bionic
      arch: arm64
      language: shell
      script: "sudo ./tests/simple.sh"
    - name: "18.04 native s390x"
      os: linux
      dist: bionic
      arch: s390x
      language: shell
      script: "sudo ./tests/simple.sh"
    - name: "18.04 native ppc64le"
      os: linux
      dist: bionic
      arch: ppc64le
      language: shell
      script: "sudo ./tests/simple.sh"
    - name: "16.04 native run (py3.5)"
      os: linux
      dist: xenial
      language: shell
      script: "sudo ./tests/simple.sh"
    - name: "nosetests and travis Python 3.5"
      os: linux
      dist: bionic
      language: python
      python: "3.5"
      install: pip install -r requirements.txt; python setup.py install;
      script:
        - "nosetests -v --with-cover --cover-package=sos --cover-html"
        - "sudo ./tests/simple.sh ~/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/python"
    - name: "nosetests and travis Python 3.6"
      os: linux
      dist: bionic
      language: python
      python: "3.6"
      install: pip install -r requirements.txt; python setup.py install;
      script:
        - "nosetests -v --with-cover --cover-package=sos --cover-html"
        - "sudo ./tests/simple.sh ~/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/python"
    - name: "nosetests and travis Python 3.7"
      os: linux
      dist: bionic
      language: python
      python: "3.7"
      install: pip install -r requirements.txt; python setup.py install;
      script:
        - "nosetests -v --with-cover --cover-package=sos --cover-html"
        - "sudo ./tests/simple.sh ~/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/python"
    - name: "nosetests and travis Python 3.8"
      os: linux
      dist: bionic
      language: python
      python: "3.8"
      install: pip install -r requirements.txt; python setup.py install;
      script:
        - "nosetests -v --with-cover --cover-package=sos --cover-html"
        - "sudo ./tests/simple.sh ~/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/python"

notifications:
  email:
    sos-devel@redhat.com
  irc:
    channels:
      - "us.freenode.net#sosreport"
    on_success: change
git:
  depth: 5
